### PR TITLE
Remove aria2c

### PR DESCRIPTION
**Pull request by jorektheglitch**

### CODE REVIEW

**Comment by x-CK-x** [comment]
did you plan on having aria2 & wget replaced in the webui,py & helper_functions.py also, or just the batch downloader for now?

**Comment by jorektheglitch** [comment]
For now it's just about batch downloader. Feels free to use FliesDownloader to replace `aria2c` everywhere it used.

**Comment by x-CK-x** [comment]
also was that gitignore auto-generated or something?    there's a lot of things in that file

**Comment by jorektheglitch** [comment]
Yes, I use slight edited .gitignore from [gitignore collection](https://github.com/github/gitignore). It covers a lot of things and simplifies developing process.

**Comment by x-CK-x** [comment]
I still need to test on Linux, but while the files were downloaded. The program after *## Checking tag search query* on windows started to loop the download of the tag csv.gz file again and then tried to reload it a second time before actually downloading images. */proxy_test/Dataset-Curation-Tool/tags-2023-05-20.csv.1.gz*

That's really the only issue happening atm. I'll let you know if it also happens on linux.

**Comment by x-CK-x** [comment]
> Yes, I use slight edited [Python.gitignore](https://github.com/github/gitignore/blob/main/Python.gitignore) from [gitignore collection](https://github.com/github/gitignore). It covers a lot of things and simplifies developing process.

I moved all the webUI downloading to helper_functions.py, can you add your proxy feature to those?

https://github.com/x-CK-x/Dataset-Curation-Tool/blob/9b98e1cdf5d930a222130e2ae0b332e35f49b9c6/helper_functions.py#L372

**Comment by jorektheglitch** [comment]
Surely. Will update PR asap.

**Comment by x-CK-x** [comment]
The webui has reached a somewhat steady-state. If you want to update the batch downloader script & the image board download functions in the helper_functions script to be compatible with using a proxy just let me know. Here or discord works.

**Pull request closed without merging**
